# https://taskfile.dev

version: "3"

vars:
  UV_PATH: $HOME/.local/bin/uv

includes:
  install:
    taskfile: taskfiles/Taskfile_{{OS}}.yml
    flatten: true

tasks:
  default:
    # desc: show tasks
    cmd: task -l
    silent: true

  uv:clean:
    desc: Remove the virtual environment
    cmds:
      - rm -rf .venv
