#!/bin/bash

echo "Quick access to containerlab devices:"
echo ""
echo "Arista devices:"
echo "docker exec -it clab-nautobot-lab-access1 FastCli"
echo "docker exec -it clab-nautobot-lab-access2 FastCli"
echo ""
echo "Nokia devices:"
echo "docker exec -it clab-nautobot-lab-dist1 sr_cli"
echo "docker exec -it clab-nautobot-lab-rtr1 sr_cli"
echo ""
echo "Linux containers:"
echo "docker exec -it clab-nautobot-lab-workstation1 sh"
echo "docker exec -it clab-nautobot-lab-mgmt sh"
echo ""
echo "Port mappings for SSH (if configured):"
echo "ssh -p 50001 admin@localhost  # access1"
echo "ssh -p 50003 admin@localhost  # access2"
echo "ssh -p 50005 admin@localhost  # dist1"
echo "ssh -p 50007 admin@localhost  # rtr1"
echo "ssh -p 50009 root@localhost   # workstation1"
echo "ssh -p 50010 root@localhost   # mgmt"
