---
# Dynamic Site Deployment Design
# Creates a complete network site with minimal input
#
# USAGE:
#   1. Go to: Jobs → Jobs → Design Builder → Run Job
#   2. Design File: Select or upload this file (site_deployment.yaml)
#   3. Context: Provide JSON with 4 variables:
#      {
#        "site_name": "Chicago Lab",
#        "site_shortcode": "CHI01",
#        "site_prefix": "172.21.0.0/16",
#        "region": "US-Central"
#      }
#   4. Click "Run Job"
#
# REQUIRED VARIABLES:
#   - site_name: Name of the site (e.g., "Chicago Lab")
#   - site_shortcode: 3 letters + 2 digits (e.g., "CHI01") - MUST be uppercase!
#   - site_prefix: IP prefix for the site (e.g., "172.21.0.0/16")
#   - region: Region name (e.g., "US-Central")
#
# WHAT GETS CREATED:
#   - Region and Site locations
#   - 2 Racks (RACK-01, RACK-02)
#   - 4 VLANs (10, 20, 30, 100)
#   - IP prefixes and management subnet (.20.0/24)
#   - 4 Devices: {shortcode}-access1, -access2, -dist1, -rtr1
#   - 2 VMs: {shortcode}-workstation1, -management
#   - All IPs: .20.11, .20.12, .20.13, .20.14, .20.15, .20.16
#   - All interfaces with VLAN configurations
#   - Cable connections between devices
#   - Site-specific config context
#
# EXAMPLES:
#   Site 1: {"site_name": "Chicago Lab", "site_shortcode": "CHI01", "site_prefix": "172.21.0.0/16", "region": "US-Central"}
#   Site 2: {"site_name": "New York Lab", "site_shortcode": "NYC01", "site_prefix": "172.22.0.0/16", "region": "US-East"}
#   Site 3: {"site_name": "LA Lab", "site_shortcode": "LAX01", "site_prefix": "172.23.0.0/16", "region": "US-West"}
#
# See: /docs/SITE_DEPLOYMENT.md for complete documentation

# Location for this site
locations:
  - "!create_or_update:name": "{{ region }}"
    location_type__name: "Region"
    status__name: "Active"
    description: "{{ region }} Region"
  
  - "!create_or_update:name": "{{ site_name }}"
    location_type__name: "Site"
    parent__name: "{{ region }}"
    status__name: "Active"
    description: "Site {{ site_shortcode }} - {{ site_name }}"

# Racks for this site
racks:
  - "!create_or_update:name": "{{ site_shortcode }}-RACK-01"
    location__name: "{{ site_name }}"
    status__name: "Active"
    u_height: 42
    description: "Primary rack for {{ site_name }}"
  
  - "!create_or_update:name": "{{ site_shortcode }}-RACK-02"
    location__name: "{{ site_name }}"
    status__name: "Active"
    u_height: 42
    description: "Secondary rack for {{ site_name }}"

# VLANs for this site (using standard VLAN IDs)
vlans:
  - "!create_or_update:vid": 10
    "!create_or_update:name": "{{ site_shortcode }}-Management"
    status__name: "Active"
    description: "Management VLAN for {{ site_name }}"
  
  - "!create_or_update:vid": 20
    "!create_or_update:name": "{{ site_shortcode }}-Data"
    status__name: "Active"
    description: "Data VLAN for {{ site_name }}"
  
  - "!create_or_update:vid": 30
    "!create_or_update:name": "{{ site_shortcode }}-Voice"
    status__name: "Active"
    description: "Voice VLAN for {{ site_name }}"
  
  - "!create_or_update:vid": 100
    "!create_or_update:name": "{{ site_shortcode }}-LabNetwork"
    status__name: "Active"
    description: "Lab network VLAN for {{ site_name }}"

# Prefixes for this site
# Calculate management subnet from site_prefix
# Example: If site_prefix is 172.21.0.0/16, management is 172.21.20.0/24
prefixes:
  - "!create_or_update:prefix": "{{ site_prefix }}"
    type: "container"
    status__name: "Active"
    description: "Container prefix for {{ site_name }}"
    rir__name: "RFC 1918"
  
  # Management subnet (using .20 third octet)
  - "!create_or_update:prefix": "{{ site_prefix.split('.')[0] }}.{{ site_prefix.split('.')[1] }}.20.0/24"
    type: "network"
    status__name: "Active"
    description: "Management network for {{ site_name }}"
    rir__name: "RFC 1918"

# Devices for this site
devices:
  # Access Switch 1
  - "!create_or_update:name": "{{ site_shortcode }}-access1"
    location__name: "{{ site_name }}"
    role__name: "Access Switch"
    device_type__manufacturer__name: "Arista"
    device_type__model: "cEOS"
    platform__name: "Arista EOS"
    rack__name: "{{ site_shortcode }}-RACK-02"
    position: 11
    face: "front"
    status__name: "Active"
    comments: "Access switch 1 for {{ site_name }}"
  
  # Access Switch 2
  - "!create_or_update:name": "{{ site_shortcode }}-access2"
    location__name: "{{ site_name }}"
    role__name: "Access Switch"
    device_type__manufacturer__name: "Arista"
    device_type__model: "cEOS"
    platform__name: "Arista EOS"
    rack__name: "{{ site_shortcode }}-RACK-02"
    position: 12
    face: "front"
    status__name: "Active"
    comments: "Access switch 2 for {{ site_name }}"
  
  # Distribution Switch
  - "!create_or_update:name": "{{ site_shortcode }}-dist1"
    location__name: "{{ site_name }}"
    role__name: "Distribution Switch"
    device_type__manufacturer__name: "Arista"
    device_type__model: "cEOS"
    platform__name: "Arista EOS"
    rack__name: "{{ site_shortcode }}-RACK-01"
    position: 15
    face: "front"
    status__name: "Active"
    comments: "Distribution switch for {{ site_name }}"
  
  # Router
  - "!create_or_update:name": "{{ site_shortcode }}-rtr1"
    location__name: "{{ site_name }}"
    role__name: "Router"
    device_type__manufacturer__name: "Arista"
    device_type__model: "cEOS"
    platform__name: "Arista EOS"
    rack__name: "{{ site_shortcode }}-RACK-01"
    position: 20
    face: "front"
    status__name: "Active"
    comments: "Router for {{ site_name }}"

# IP Addresses for devices
# Using the management subnet calculated above
ip_addresses:
  - "!create_or_update:address": "{{ site_prefix.split('.')[0] }}.{{ site_prefix.split('.')[1] }}.20.11/24"
    status__name: "Active"
    dns_name: "{{ site_shortcode }}-access1.{{ site_name | lower | replace(' ', '-') }}"
    description: "Primary IP for {{ site_shortcode }}-access1"
  
  - "!create_or_update:address": "{{ site_prefix.split('.')[0] }}.{{ site_prefix.split('.')[1] }}.20.12/24"
    status__name: "Active"
    dns_name: "{{ site_shortcode }}-access2.{{ site_name | lower | replace(' ', '-') }}"
    description: "Primary IP for {{ site_shortcode }}-access2"
  
  - "!create_or_update:address": "{{ site_prefix.split('.')[0] }}.{{ site_prefix.split('.')[1] }}.20.13/24"
    status__name: "Active"
    dns_name: "{{ site_shortcode }}-dist1.{{ site_name | lower | replace(' ', '-') }}"
    description: "Primary IP for {{ site_shortcode }}-dist1"
  
  - "!create_or_update:address": "{{ site_prefix.split('.')[0] }}.{{ site_prefix.split('.')[1] }}.20.14/24"
    status__name: "Active"
    dns_name: "{{ site_shortcode }}-rtr1.{{ site_name | lower | replace(' ', '-') }}"
    description: "Primary IP for {{ site_shortcode }}-rtr1"

# Virtual Machines for this site
virtual_machines:
  - "!create_or_update:name": "{{ site_shortcode }}-workstation1"
    cluster__name: "Lab-Cluster"
    role__name: "Workstation"
    platform__name: "Alpine Linux"
    status__name: "Active"
    comments: "Workstation for {{ site_name }}"
  
  - "!create_or_update:name": "{{ site_shortcode }}-management"
    cluster__name: "Lab-Cluster"
    role__name: "Management"
    platform__name: "Alpine Linux"
    status__name: "Active"
    comments: "Management server for {{ site_name }}"

# VM IP Addresses
ip_addresses:
  - "!create_or_update:address": "{{ site_prefix.split('.')[0] }}.{{ site_prefix.split('.')[1] }}.20.15/24"
    status__name: "Active"
    dns_name: "{{ site_shortcode }}-workstation1.{{ site_name | lower | replace(' ', '-') }}"
    description: "Primary IP for {{ site_shortcode }}-workstation1"
  
  - "!create_or_update:address": "{{ site_prefix.split('.')[0] }}.{{ site_prefix.split('.')[1] }}.20.16/24"
    status__name: "Active"
    dns_name: "{{ site_shortcode }}-management.{{ site_name | lower | replace(' ', '-') }}"
    description: "Primary IP for {{ site_shortcode }}-management"

# Interfaces for devices
# Note: Using Design Builder's interface support (simplified)
interfaces:
  # dist1 interfaces
  - "!create_or_update:device__name": "{{ site_shortcode }}-dist1"
    "!create_or_update:name": "Management0"
    type: "1000base-t"
    status__name: "Active"
    description: "Management interface"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-dist1"
    "!create_or_update:name": "Ethernet1"
    type: "1000base-t"
    status__name: "Active"
    description: "Connected to {{ site_shortcode }}-access1"
    mode: "tagged"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-dist1"
    "!create_or_update:name": "Ethernet2"
    type: "1000base-t"
    status__name: "Active"
    description: "Connected to {{ site_shortcode }}-access2"
    mode: "tagged"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-dist1"
    "!create_or_update:name": "Ethernet3"
    type: "1000base-t"
    status__name: "Active"
    description: "Connected to {{ site_shortcode }}-rtr1"
    mode: "tagged"
  
  # access1 interfaces
  - "!create_or_update:device__name": "{{ site_shortcode }}-access1"
    "!create_or_update:name": "Management0"
    type: "1000base-t"
    status__name: "Active"
    description: "Management interface"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-access1"
    "!create_or_update:name": "Ethernet1"
    type: "1000base-t"
    status__name: "Active"
    description: "Uplink to {{ site_shortcode }}-dist1"
    mode: "tagged"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-access1"
    "!create_or_update:name": "Ethernet2"
    type: "1000base-t"
    status__name: "Active"
    description: "Connected to {{ site_shortcode }}-workstation1"
    mode: "access"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-access1"
    "!create_or_update:name": "Ethernet3"
    type: "1000base-t"
    status__name: "Active"
    description: "Available for connections"
  
  # access2 interfaces
  - "!create_or_update:device__name": "{{ site_shortcode }}-access2"
    "!create_or_update:name": "Management0"
    type: "1000base-t"
    status__name: "Active"
    description: "Management interface"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-access2"
    "!create_or_update:name": "Ethernet1"
    type: "1000base-t"
    status__name: "Active"
    description: "Connected to {{ site_shortcode }}-dist1"
    mode: "tagged-all"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-access2"
    "!create_or_update:name": "Ethernet2"
    type: "1000base-t"
    status__name: "Active"
    description: "Available for connections"
    mode: "access"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-access2"
    "!create_or_update:name": "Ethernet3"
    type: "1000base-t"
    status__name: "Active"
    description: "Available for connections"
    mode: "access"
  
  # rtr1 interfaces
  - "!create_or_update:device__name": "{{ site_shortcode }}-rtr1"
    "!create_or_update:name": "Management0"
    type: "1000base-t"
    status__name: "Active"
    description: "Management interface"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-rtr1"
    "!create_or_update:name": "Ethernet1"
    type: "1000base-t"
    status__name: "Active"
    description: "Uplink to {{ site_shortcode }}-dist1"
    mode: "tagged"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-rtr1"
    "!create_or_update:name": "Ethernet2"
    type: "1000base-t"
    status__name: "Active"
    description: "Connected to {{ site_shortcode }}-management"
    mode: "access"
  
  - "!create_or_update:device__name": "{{ site_shortcode }}-rtr1"
    "!create_or_update:name": "Ethernet3"
    type: "1000base-t"
    status__name: "Active"
    description: "Available for connections"

# Cables (connections between devices)
cables:
  # Access switches to Distribution switch
  - termination_a_type: "dcim.interface"
    termination_a:
      "!get:device__name": "{{ site_shortcode }}-access1"
      "!get:name": "Ethernet1"
    termination_b_type: "dcim.interface"
    termination_b:
      "!get:device__name": "{{ site_shortcode }}-dist1"
      "!get:name": "Ethernet1"
    status__name: "Connected"
    label: "{{ site_shortcode }}-access1:Ethernet1 to {{ site_shortcode }}-dist1:Ethernet1"
  
  - termination_a_type: "dcim.interface"
    termination_a:
      "!get:device__name": "{{ site_shortcode }}-access2"
      "!get:name": "Ethernet1"
    termination_b_type: "dcim.interface"
    termination_b:
      "!get:device__name": "{{ site_shortcode }}-dist1"
      "!get:name": "Ethernet2"
    status__name: "Connected"
    label: "{{ site_shortcode }}-access2:Ethernet1 to {{ site_shortcode }}-dist1:Ethernet2"
  
  # Distribution switch to Router
  - termination_a_type: "dcim.interface"
    termination_a:
      "!get:device__name": "{{ site_shortcode }}-dist1"
      "!get:name": "Ethernet3"
    termination_b_type: "dcim.interface"
    termination_b:
      "!get:device__name": "{{ site_shortcode }}-rtr1"
      "!get:name": "Ethernet1"
    status__name: "Connected"
    label: "{{ site_shortcode }}-dist1:Ethernet3 to {{ site_shortcode }}-rtr1:Ethernet1"

# Config Context for this site
config_contexts:
  - "!create_or_update:name": "{{ site_name }} Common Configuration"
    weight: 1000
    description: "Common configuration for {{ site_name }}"
    is_active: true
    data:
      site_shortcode: "{{ site_shortcode }}"
      ntp_servers:
        - "{{ site_prefix.split('.')[0] }}.{{ site_prefix.split('.')[1] }}.20.1"
        - "time.google.com"
      dns_servers:
        - "8.8.8.8"
        - "8.8.4.4"
      syslog_hosts:
        - host: "{{ site_prefix.split('.')[0] }}.{{ site_prefix.split('.')[1] }}.20.1"
          port: 514
      snmp:
        community: "{{ site_shortcode }}_ro"
        location: "{{ site_name }}"
      timezone: "UTC"
      domain_name: "{{ site_name | lower | replace(' ', '-') }}.local"
    locations:
      - "!get:name": "{{ site_name }}"

